name = "cybertools"
main = "src/index.js"
compatibility_date = "2023-12-01"

[env.production]
name = "cybertools"
routes = [
  { pattern = "cybertools.snap-view.com/*", zone_name = "snap-view.com" }
]

[env.development]
name = "cybertools-dev"

[[env.production.rules]]
type = "ESModule"
globs = ["**/*.js"]

[[env.development.rules]]
type = "ESModule"
globs = ["**/*.js"]