---
name: Bug Report
about: Create a report to help us improve CyberTools
title: '[BUG] '
labels: ['bug']
assignees: ''

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Tool Information:**
- Tool Name: [e.g. WHOIS Lookup Tool]
- Tool Type: [Production/Development]
- Input Used: [What you entered into the tool]

**Environment (please complete the following information):**
- OS: [e.g. iOS]
- Browser [e.g. chrome, safari]
- Version [e.g. 22]
- Device: [e.g. Desktop, Mobile]

**Additional context**
Add any other context about the problem here.

**Security Note**
⚠️ Please do not include sensitive information like real IP addresses, domains you don't own, or any confidential data in this bug report.