name: Test Production Tools

on:
  push:
    branches: [ main, copilot/fix-12 ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Generate coverage report
      run: npm run test:coverage

    - name: Upload coverage to Codecov
      if: matrix.node-version == '20.x'
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage
        fail_ci_if_error: true

    - name: Run Cloudflare verification
      run: npm run verify
      continue-on-error: true

  validate-tools:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Validate WHOIS tool structure
      run: |
        test -f "Prod/WHOIS Lookup Tool/index.html" || { echo "WHOIS HTML missing"; exit 1; }
        test -f "Prod/WHOIS Lookup Tool/script.js" || { echo "WHOIS script missing"; exit 1; }
        test -f "Prod/WHOIS Lookup Tool/styles.css" || { echo "WHOIS styles missing"; exit 1; }
        echo "WHOIS Lookup Tool structure validated"

    - name: Validate DNS tool structure  
      run: |
        test -f "Prod/DNS poisoning checker/index.html" || { echo "DNS HTML missing"; exit 1; }
        test -f "Prod/DNS poisoning checker/script.js" || { echo "DNS script missing"; exit 1; }
        test -f "Prod/DNS poisoning checker/styles.css" || { echo "DNS styles missing"; exit 1; }
        echo "DNS Poisoning Checker structure validated"

    - name: Check HTML validity
      run: |
        # Basic HTML validation
        grep -q "<!DOCTYPE html>" "Prod/WHOIS Lookup Tool/index.html" || { echo "WHOIS HTML missing DOCTYPE"; exit 1; }
        grep -q "<!DOCTYPE html>" "Prod/DNS poisoning checker/index.html" || { echo "DNS HTML missing DOCTYPE"; exit 1; }
        echo "HTML structure validation passed"